### ISSUE TITLE
震动中，如何取消震动

### ISSUE THREAD

**Issue by kingiol** [bjlinhong/RongCallVibrate#1]
用户收到APNs推送，开始震动，

然后用户进入主app，该如何取消震动？

在主应用中调用： AudioServicesDisposeSystemSoundID(kSystemSoundID_Vibrate)，可是无效。

**Comment by bjlinhong** [comment]
打开app之前需要将 NotificationService 中 triggerVibrateRCCall方法中的 timer 停止,
您可以尝试下在 serviceExtensionTimeWillExpire 方法中将timer停止,
但停止的时机未经验证, 无法给出准确结论.

**Comment by kingiol** [comment]
@bjlinhong 谢谢回复，取消震动可以搞定了，可以使用AppGroup，主app设置AppGroup，extension可以在timer里面监听，然后可以执行取消操作。

现在遇到了第二个问题，就是这个extension震动只在iOS 14+的iphone上面起效果，我测试了iOS 13和iOS 12发现代码执行了，却无法震动，请问一下你那边是不是也是这样的情况？谢谢。

**Comment by bjlinhong** [comment]
> @bjlinhong 谢谢回复，取消震动可以搞定了，可以使用AppGroup，主app设置AppGroup，extension可以在timer里面监听，然后可以执行取消操作。
> 
> 现在遇到了第二个问题，就是这个extension震动只在iOS 14+的iphone上面起效果，我测试了iOS 13和iOS 12发现代码执行了，却无法震动，请问一下你那边是不是也是这样的情况？谢谢。

AppGroup控制是个好办法, 我这里还没有试过, 谢谢你的提示.
第二个问题, 在 extension 中震动是否可用是受iOS系统对震动方法控制的, 我记得我这里iOS12 13时是可以震动的
